### PR TITLE
Add fixture method to footy.

### LINKED ISSUE #2: Add System Tests to the Project
Add unit tests to ensure that the background tests are maintained with regression tests.

### LINKED ISSUE #10: Refactor Code and Externalise matplotlib Code
This issue has been raised to implement the suggestions in PR #9.  This was to:

- Replace the outcome_probability and score_probability with methods called fixture (for games yet to be played) and result (for games for which the result is known). These will return a dict of details to ensure that we actually get the full set of Brier scores for the match outcome, predicted goals against actual goals scored by the home and away team and the predicted score (e.g. 2 - 0).
- Externalise the plotting functions so they're not actually part of the Footy class (for now put that code into the Jupyter notebook.

### PR DESCRIPTION
**Pull request by dallinb**
# Overview

Add fixture method to footy.  Also removes the `outcome_probability` and `score_probability` methods as their logic is replaced by the new method.

Also increases test coverage from 70% to 99%.

Externalised plotting into the Jupyter notebook (preview at https://github.com/FootyStats/footy/blob/feature/fixture_method/background.ipynb).

# Issues Closed by this PR
- Fixes #2
- Fixes #10.

# TODO

- [x] Add in logic for when there is not enough data to make predictions.
- [ ] Remove reference to removed methods

### CODE REVIEW

**Comment by dallinb** [comment]
Changes added in 92f03a82ee0c6d3fd2ad8ca14cfeff747e55f548 add a narrative test of a dummy league.  I strongly suspect that you will be able to suggest improvements to how this can be carried out, but it does cover what happens when we don't have enough data to calculate probabilities.  It has also bumped the test coverage from 80% (which had already improved from 70%) to 99%!

**Comment by SebDuff** [comment]
Unable to comment on unchanged lines so adding here

Lines 58-62 in __init__.py refer to removed methods
 ```
   >>> widget.score_probability('Arsenal', 'Stoke').head()
    Plot the outcome probability
    >>> widget.outcome_probability('Arsenal', 'Stoke')
```

**Review by SebDuff — CHANGES_REQUESTED** [review]
Unable to comment on unchanged lines so adding here

Lines 58-62 in __init__.py refer to removed methods
 ```
   >>> widget.score_probability('Arsenal', 'Stoke').head()
    Plot the outcome probability
    >>> widget.outcome_probability('Arsenal', 'Stoke')
```

**Comment by dallinb** [comment]
> Unable to comment on unchanged lines so adding here
> 
> Lines 58-62 in **init**.py refer to removed methods
> 
> ```
>   >>> widget.score_probability('Arsenal', 'Stoke').head()
>    Plot the outcome probability
>    >>> widget.outcome_probability('Arsenal', 'Stoke')
> ```

Sorry, I didn't explain this so well.  Covid-19 is not helping us to get together to show this in better detail.  This was shifted to the Jupyter notebook.  If you look at the changes in the notebook (specifically on this branch at https://github.com/FootyStats/footy/blob/feature/fixture_method/background.ipynb and see the sub-section labelled _Goal Probability_.  In that example, you see the code that takes the response from the new `fixture` method.  This looks like this:

```python
response = f.fixture(home_team, away_team)
home_team_goals_probability = response['home_team_goals_probability']
away_team_goals_probability = response['away_team_goals_probability']

fig, ax = plt.subplots()
width = 0.3
ax.bar(np.arange(len(home_team_goals_probability)),
       home_team_goals_probability, width=width, label=home_team)

ax.bar(np.arange(len(away_team_goals_probability)) + width,
       away_team_goals_probability,
       width=width,
       label=away_team)
ax.set_title(f'{home_team} v. {away_team}')
ax.set_xlabel('Probable Goals')
ax.set_ylabel('Probability')
ax.legend()
fig.tight_layout()
plt.show()

response['final_score_probabilities']
```

This code not only plots the goal probability for both the home and away team (as a bar chart), but also outputs the final score probability (as a DataFrame).

To confirm the figures returned also matched the figures from the original implementation and therefore matched the figures from the reference article.

**Comment by dallinb** [comment]
Well spotted and keep up the good work!  Updated the docstring and by extension the documentation.  A preview of the documentation is available at https://github.com/FootyStats/footy/blob/feature/fixture_method/docs/index.md#examples

**Review by SebDuff — APPROVED** [review]
LGTM

**Pull request merged**
